name: Home
version: ${project.version}
main: de.gamekuchen.home.Main
api-version: 1.13

commands:
  sethome:
    description: "Setzt dein Home"
  home:
    description: "Teleportiert dich zu deinem Home!"
  delhome:
    description: "Löscht dein Home"

